apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: longsan-namespace
  labels:
    longsan: order
spec:
  selector:
    matchLabels:
      longsan: order
  template:
    metadata:
      labels:
        longsan: order
    spec:
      containers:
        - name: order-app
          image: longsanx/longsan-order:1.0
          ports:
            - containerPort: 9004