apiVersion: v1
kind: Service
metadata:
  name: order-app
  namespace: longsan-namespace
spec:
  type: NodePort
  selector:
    longsan: order
  ports:
    - port: 9004
      targetPort: 9004
      protocol: TCP
      nodePort: 30114