apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: longsan-namespace
spec:
  type: NodePort
  selector:
    longsan: user
  ports:
    - port: 9003
      targetPort: 9003
      protocol: TCP
      nodePort: 30003