#nacos:
##  配置中心
#  config:
#    server-addr: 127.0.0.1:8848
#    username: nacos
#    password: nacos
##    注册中心
#  discovery:
#    server-addr: 127.0.0.1:8848
#    username: nacos
#    password: nacos
server:
  port: 9002
spring:
  application:
    name: local_nacos
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yaml
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos