server:
  port: 7888
spring:
  application:
    name: producer
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        file-extension: yaml
        import-check:
          enabled: false
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
logging:
  level:
    root: INFO           # 默认日志级别
  file:
    name: logs/app.log   # 输出到指定文件
management:
  endpoints:
    web:
      exposure:
        include: loggers # 动态调整日志级别